# config for analysis

# most CPUs to ever use at once
max_cpus: 16

# amplicons sequenced by PacBio (need for bc mapping even though we're not building PacBio reads)
amplicons_PRD-0038: data/PacBio_amplicon_PRD0038.gb

# how to parse the amplicon
feature_parse_specs_PRD-0038: data/feature_parse_specs_PRD0038.yaml


# do we get the sequencing data from the 'HutchServer' or 'SRA'?
seqdata_source: HutchServer


# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene (for SARS2) -- can't remember if this is used at all?
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering

# pdbs for mapping, analysis
pdb_6m0j: data/6m0j.pdb

# URLs from which we download binding & expression of mutants & variants from prior experiments
WH1_mut_antibody_escape_url: https://media.githubusercontent.com/media/jbloomlab/SARS2_RBD_Ab_escape_maps/main/processed_data/escape_data.csv
SARSr_lib40_mut_bind_expr_url: https://raw.githubusercontent.com/jbloomlab/SARSr-CoV-RBD_DMS/main/results/final_variant_scores/final_variant_scores_lib40_41.csv?token=GHSAT0AAAAAABXD2PZJDNEGYB4ZNFIREZDQZASJ3LQ
SARSr_lib47_mut_bind_expr_url: https://raw.githubusercontent.com/jbloomlab/SARSr-CoV_homolog_survey/master/results/final_variant_scores/wt_variant_scores.csv
SARS2_WH1_BA2_mut_bind_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS_Omicron/main/results/final_variant_scores/final_variant_scores.csv

# list of the primary targets for which we are calling mutations in lib47
targets_ordered:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - BM48-31
  - BB9904
  - BtKY72
  - PRD-0038
  - PDF-2370
  - Khosta-1
  - Khosta-2
  - RhGB01
  - RsYN04
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS2c_MAP
  - SARS-CoV-2_WH1
  - SARS-CoV-2_Alpha
  - SARS-CoV-2_Beta
  - SARS-CoV-2_Delta
  - SARS-CoV-2_BA2
  - BANAL-20-103
  - BANAL-20-236
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - RshSTT182
  - Rc-o319
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - YN2020B
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3


EurAf_extant:
  - BM48-31
  - BB9904
  - BtKY72
  - PRD-0038
  - PDF-2370
  - Khosta-1
  - Khosta-2
  - RhGB01
  
RsYN04_extant:
  - RsYN04

SARS2_extant:
  - SARS-CoV-2_WH1
  - SARS-CoV-2_Alpha
  - SARS-CoV-2_Beta
  - SARS-CoV-2_Delta
  - SARS-CoV-2_BA2
  - BANAL-20-103
  - BANAL-20-236
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - RshSTT182
  - Rc-o319
  
SARS1_extant:
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - YN2020B
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084

Clade2_extant:
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3

ancestors_MAP:
  - AncSarbecovirus_MAP
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - AncSARS1a_MAP
  - Rs7327
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncClade2_MAP
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  
ancestors_MAP_v_alt:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only

#annotations about RBD sites
RBD_annotation_file: data/RBD_sites.csv
 
# output directories / files
summary_dir: results/summary
figs_dir: results/figures

#downloads of prior data
SARSr_lib40_mut_bind_expr: results/prior_DMS_data/SARSr-lib40_mutant_ACE2binding_expression.csv
SARSr_lib47_mut_bind_expr: results/prior_DMS_data/SARSr-lib47_wts_ACE2binding_expression.csv
SARS2_WH1_BA2_mut_bind_expr: results/prior_DMS_data/SARS2-WH1-BA2_ACE2binding_expression.csv
WH1_mut_antibody_escape: results/prior_DMS_data/WH1_mutant_antibody-escape.csv

#manually compiled pool of barcode-variant lookups:
codon_variant_table: data/bc_variant_lookup_pooled.csv

counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv

sera_delta_AUC_dir: results/bc_sera_binding/
sera_delta_AUC_file: results/bc_sera_binding/bc_sera_binding.csv

final_variant_scores_dir: results/final_variant_scores/
final_variant_scores_dms_file: results/final_variant_scores/final_variant_scores_dms.csv
final_variant_scores_wts_file: results/final_variant_scores/final_variant_scores_wts.csv

epitopes_dir: results/serum_epitopes

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0
